#:import config frontend.screens.config

<StartScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Header
        BoxLayout:
            size_hint_y: 0.15
            Label:
                text: "Neues Spiel neues Glück!"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_BIG)

        # Explanation Label
        Label:
            size_hint_y: 0.1
            text: "Namen der Spieler eingeben:"
            font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)

        # Body
        BoxLayout:
            id: player_inputs_container
            orientation: 'vertical'
            size_hint_y: 0.60

        # Footer
        BoxLayout:
            size_hint_y: 0.15
            Button:
                text: "Spiel starten"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.start_game(self)

<ScoreboardScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Header
        BoxLayout:
            size_hint_y: 0.15
            Label:
                text: f"Punktestand Runde {root.current_round_number}"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_BIG)

        # Body
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.70
            GridLayout:
                id: scoreboard
                cols: 3
                spacing: 0
                row_default_height: self.parent.height * 0.15

        # Footer
        BoxLayout:
            size_hint_y: 0.15
            Button:
                text: "Punkte eingeben"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.go_to_add_points(self)

<AddPointsScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Header
        BoxLayout:
            size_hint_y: 0.15
            orientation: 'vertical'
            Label:
                text: f"Eingabe für Runde {root.current_round_number}"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_BIG)

        # Table Header
        GridLayout:
            size_hint_y: 0.1
            cols: 4
            Label:
                text: "Spieler"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
            Label:
                text: "Punkte"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
            Label:
                text: "# Verdopplungen"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
            Label:
                text: "Gewinner"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)

        # Body
        BoxLayout:
            id: players_layout
            orientation: 'vertical'
            size_hint_y: 0.60

        # Footer
        BoxLayout:
            id: buttons_layout
            size_hint_y: 0.15
            orientation: 'horizontal'
            spacing: 10
            Button:
                text: "Punkte berechnen"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.submit_points()

<RoundSummaryScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Header
        BoxLayout:
            size_hint_y: 0.15
            Label:
                text: f"Rundenübersicht Runde {root.current_round_number}"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_BIG)

        # Table Header
        GridLayout:
            size_hint_y: 0.1
            cols: 3
            Label:
                text: "Spieler"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
            Label:
                text: "Rundenpunkte"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
            Label:
                text: "Punkteänderung"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)

        # Body
        BoxLayout:
            id: summary_layout
            orientation: 'vertical'
            size_hint_y: 0.60

        # Footer
        BoxLayout:
            size_hint_y: 0.15
            Button:
                text: "Punkte anwenden"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.confirm_points()

<GameOverScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Header
        BoxLayout:
            size_hint_y: 0.15
            Label:
                text: root.winner_text
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_BIG)
                bold: True

        # Body
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.70
            GridLayout:
                id: scoreboard
                cols: 3
                spacing: 0
                row_default_height: self.parent.height * 0.15

        # Footer
        BoxLayout:
            size_hint_y: 0.15
            Button:
                text: "Spielauswertung"
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.proceed_to_save_game()

<SaveGameScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20

        # Body
        BoxLayout:
            id: save_container
            orientation: 'vertical'
            size_hint_y: 0.8

        # Footer
        BoxLayout:
            size_hint_y: 0.2
            Button:
                id: save_button
                text: 'Spiel speichern'
                font_size: config.get_font_size(config.FONT_SIZE_RATIO_MEDIUM)
                on_release: root.save_game()

<StatsScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 20
        
        # Body
        BoxLayout:
            id: stats_container
            orientation: 'vertical'
            size_hint_y: 1.0
