name: Build Cross-Platform Executables

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            output_name: MyJongg Calculator.exe
            artifact_name: MyJongg-Calculator-Windows
            build_script: build_windows.bat
          - os: ubuntu-latest
            output_name: MyJongg-Calculator
            artifact_name: MyJongg-Calculator-Linux
            build_script: ./build_linux.sh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Linux-specific: Install system dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libmtdev-dev xclip xsel

      # Install Python dependencies
      - name: Install Python dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install --upgrade pip
          pip install -r requirements.lock
          pip install pyinstaller

      - name: Install Python dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pip install --upgrade pip
          pip install -r requirements.lock
          pip install pyinstaller kivy_deps.sdl2 kivy_deps.glew

      # Make build script executable on Linux
      - name: Make build script executable
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x build_linux.sh

      # Build the executable
      - name: Build executable
        run: ${{ matrix.build_script }}

      # Upload artifacts
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            dist/${{ matrix.output_name }}
          retention-days: 90

  # Create a GitHub release if this was triggered by a tag
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: MyJongg-Calculator-Windows
          path: ./release-windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: MyJongg-Calculator-Linux
          path: ./release-linux

      # Make Linux binary executable
      - name: Make Linux binary executable
        run: chmod +x ./release-linux/MyJongg-Calculator

      # Create zip archives for easier distribution
      - name: Create Windows zip
        run: |
          cd release-windows
          zip -r ../MyJongg-Calculator-Windows.zip "MyJongg Calculator.exe"

      - name: Create Linux tar.gz
        run: |
          cd release-linux
          tar -czf ../MyJongg-Calculator-Linux.tar.gz MyJongg-Calculator

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            MyJongg-Calculator-Windows.zip
            MyJongg-Calculator-Linux.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## MyJongg Calculator ${{ github.ref_name }}
            
            Cross-platform Mahjong score calculator.
            
            ### Downloads
            - **Windows**: MyJongg-Calculator-Windows.zip
            - **Linux**: MyJongg-Calculator-Linux.tar.gz
            
            ### Installation
            
            **Windows:**
            1. Download and extract the zip file
            2. Run `MyJongg Calculator.exe`
            
            **Linux:**
            1. Download and extract: `tar -xzf MyJongg-Calculator-Linux.tar.gz`
            2. Make executable: `chmod +x MyJongg-Calculator`
            3. Run: `./MyJongg-Calculator`
            
            ### System Requirements
            - **Windows**: Windows 10 or later
            - **Linux**: Ubuntu 20.04+, Fedora 35+, or equivalent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

