name: Build Linux Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libmtdev-dev \
          xclip \
          xsel \
          libegl1-mesa-dev \
          libgles2-mesa-dev
          
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Install Python dependencies
      run: |
        uv pip install --system -e .
        uv pip install --system pyinstaller==6.11.1
        
    - name: Build Linux binary
      run: |
        pyinstaller app_linux.spec
        
    - name: Create artifact directory
      run: |
        mkdir -p artifacts
        cp dist/MyJongg-Calculator artifacts/
        chmod +x artifacts/MyJongg-Calculator
        
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: MyJongg-Calculator-Linux
        path: artifacts/MyJongg-Calculator
        retention-days: 90
        
    - name: Create release archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd artifacts
        tar -czf MyJongg-Calculator-Linux-x86_64.tar.gz MyJongg-Calculator
        
    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/MyJongg-Calculator-Linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

